[package]
name = "colink-protocol-telegram-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
colink-sdk = { tag = "v0.1.13", git = "ssh://git@github.com/CoLearn-Dev/colink-sdk-rust-dev.git" }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = "1.18"
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }
